/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"
#include "../../../3rdparty/fatfs-0.13/source/ff.h"
#include "src/gfile/gfile_fs.h"
#include "./cornerWidget/corner.h"
#include "./dialWidget/dial.h"
#include "./fuelGauge/fuelGauge.h"

// GListeners
extern GListener glistener;

// GHandles
extern GHandle ghContainerPage0;
extern GHandle ghLabel1;
extern GHandle ghLabel2;
extern GHandle ghLabel3;
extern GHandle ghLabel4;
extern GHandle ghLabel5;
extern GHandle ghLabel6;
extern GHandle ghLabel7;
extern GHandle ghLabel8;
extern GHandle _ghDial;
extern gdispImage _imgDialFace;
extern GTimer _gtimer;
extern GHandle ghCorner1;
extern GHandle ghCorner2;
extern GHandle ghCorner3;
extern GHandle ghCorner4;
extern GHandle tempProgressBar;
extern GHandle oilProgressBar;
mutex_t mtx1;
bool_t zeroAll;

// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);

#endif /* _GUI_H_ */

