/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#include "gui.h"
#include "gfx.h"
#include "can_id_transformer.h"
#include "qspiFlash.h"
#include "fileLayout.h"
#include "stdio.h"
#include "modbus_thread/modbus_thread.h"
#include "lwip/sockets.h"
#include "lwipthread.h"
#include "web/web.h"

/*
 * Internal loopback mode, 500KBaud, automatic wakeup, automatic recover
 */
//static const CANConfig cancfg = {
//  CAN_MCR_ABOM | CAN_MCR_AWUM | CAN_MCR_TXFP,
//  CAN_BTR_LBKM | CAN_BTR_SJW(0) | CAN_BTR_TS2(2) |
//  CAN_BTR_TS1(3) | CAN_BTR_BRP(17)
//};

/*
 * Watchdog deadline set to more than one second (LSI=40000 / (64 * 1000)).
 */
static const WDGConfig wdgcfg = {
  STM32_IWDG_PR_64,
  STM32_IWDG_RL(1000),
  STM32_IWDG_WIN_DISABLED
};

/*
 * normal mode, 250KBaud, ....
 * APB1 36MHz CAN1 D15-PB8(RX) D14-PB9(TX)
 */
static const CANConfig cancfg = {
  CAN_MCR_ABOM | CAN_MCR_AWUM | CAN_MCR_TXFP,
  CAN_BTR_SJW(0) | CAN_BTR_TS2(2) |
  CAN_BTR_TS1(3) | CAN_BTR_BRP(17)
};

/*
 * Receiver thread.
 */
static THD_WORKING_AREA(can_rx1_wa, 2048);
static THD_FUNCTION(can_rx, p) {
  CANDriver *cip = p;
  event_listener_t el;
  CANRxFrame rxmsg;

  (void)p;
  chRegSetThreadName("receiver");
  chEvtRegister(&cip->rxfull_event, &el, 0);
  while(!chThdShouldTerminateX()) {
    if (chEvtWaitAnyTimeout(ALL_EVENTS, MS2ST(200)) == 0) {
      chMtxLock(&mtx1);
      zeroAll = true;
      chMtxUnlock(&mtx1);
      continue;
    }
    while (canReceive(cip, CAN_ANY_MAILBOX,
                      &rxmsg, TIME_IMMEDIATE) == MSG_OK) {
      if(rxmsg.IDE == CAN_IDE_EXT) {
        switch(rxmsg.EID) {
        case 0x18FEEF00: {
          float temp = transformOilPressure(rxmsg.data8, rxmsg.DLC);
          chMtxLock(&mtx1);
          cornerSetValue(ghCorner2, temp);
          gwinProgressbarSetPosition(oilProgressBar, temp*10);
          chMtxUnlock(&mtx1);
          break;
        }
        case 0x18FEEE00: {
          uint32_t temp = transformCoolantTemperature(rxmsg.data8, rxmsg.DLC);
          chMtxLock(&mtx1);
          gwinProgressbarSetPosition(tempProgressBar, temp);
          cornerSetValue(ghCorner4, temp);
          chMtxUnlock(&mtx1);
          break;
        }
        case 0x18FEF700: {
          float temp = transformBatteryVoltage(rxmsg.data8, rxmsg.DLC);
          chMtxLock(&mtx1);
          cornerSetValue(ghCorner1, temp);
          chMtxUnlock(&mtx1);
          break;
        }
        case 0x18FEFC00: {
          // fuel level
          break;
        }
        case 0x0CF00400: {
          uint32_t temp = transformEngineSpeed(rxmsg.data8, rxmsg.DLC);
          if(temp != 0) {
            dialSetValue(_ghDial, temp);
//            chThdSleepMilliseconds(50);
          }
          break;
        }
        default:
          break;
        }
      }
    }
  }
  chEvtUnregister(&CAND1.rxfull_event, &el);
}

/*
 * Transmitter thread.
 */
static THD_WORKING_AREA(can_tx_wa, 256);
static THD_FUNCTION(can_tx, p) {
  CANTxFrame txmsg;

  (void)p;
  chRegSetThreadName("transmitter");
  txmsg.IDE = CAN_IDE_EXT;
  txmsg.EID = 0x0CF00400;
  txmsg.RTR = CAN_RTR_DATA;
  txmsg.DLC = 8;
  txmsg.data8[0] = 0xF0;
  txmsg.data8[1] = 0x7D;
  txmsg.data8[2] = 0x84;
  txmsg.data8[3] = 0xB8;
  txmsg.data8[4] = 0x12;
  txmsg.data8[5] = 0x00;
  txmsg.data8[6] = 0xF3;
  txmsg.data8[7] = 0x84;



  while (!chThdShouldTerminateX()) {
    canTransmit(&CAND1, CAN_ANY_MAILBOX, &txmsg, MS2ST(100));
    chThdSleepMilliseconds(10);
  }
}

static THD_WORKING_AREA(can_tx2_wa, 256);
static THD_FUNCTION(can_tx2, p) {
  CANTxFrame txmsg;

  (void)p;

  txmsg.IDE = CAN_IDE_EXT;
  txmsg.EID = 0x18FEF700;
  txmsg.RTR = CAN_RTR_DATA;
  txmsg.DLC = 8;
  txmsg.data8[0] = 0xFF;
  txmsg.data8[1] = 0xFF;
  txmsg.data8[2] = 0xFF;
  txmsg.data8[3] = 0xFF;
  txmsg.data8[4] = 0xFF;
  txmsg.data8[5] = 0xFF;
  txmsg.data8[6] = 0x33;
  txmsg.data8[7] = 0x02;

  while (!chThdShouldTerminateX()) {
    canTransmit(&CAND1, CAN_ANY_MAILBOX, &txmsg, MS2ST(100));
    chThdSleepMilliseconds(800);
  }
}

int main(int argc, char* argv[])
{

    gfxInit();
    lwipInit(NULL);
    chMtxObjectInit(&mtx1);
    gdispSetDisplay(gdispGetDisplay(0));

//	gdispSetBacklight(100);
//	gdispSetContrast(100);

	geventListenerInit(&glistener);
	gwinAttachListener(&glistener);


//    writeImagesToFlash();
//	writeUgfxImageFromROMtoFatFS("S|logo.png", "F|logo");

	guiCreate();

	/*
	   * Starting the watchdog driver.
	   */
    wdgStart(&WDGD1, &wdgcfg);

	canStart(&CAND1, &cancfg);
	chThdCreateStatic(can_rx1_wa, sizeof(can_rx1_wa), NORMALPRIO + 7,
	                    can_rx, (void *)&CAND1);
	/*
     * Creates the HTTP thread (it changes priority internally).
     */
//    chThdCreateStatic(wa_http_server, sizeof(wa_http_server), NORMALPRIO + 1,
//                      http_server, NULL);

	chThdCreateStatic(modbus_thread_size, sizeof(modbus_thread_size), MODBUS_THREAD_PRIORITY,
	                  modbus_server, NULL);


//	chThdCreateStatic(can_tx_wa, sizeof(can_tx_wa), NORMALPRIO + 7,
//	                    can_tx, NULL);
//	chThdCreateStatic(can_tx2_wa, sizeof(can_tx2_wa), NORMALPRIO + 7,
//	                        can_tx2, NULL);
	while (1) {
	  guiEventLoop();
	}

	return 0;
}

void writeImagesToFlash() {
    formatQuadFlash();
    writeUgfxImageFromROMtoFatFS("S|logo.png", "F|logo");
    writeUgfxImageFromROMtoFatFS("S|tahometer.png", "F|tahometer");
    writeUgfxImageFromROMtoFatFS("S|corner1.png", "F|corner1");
    writeUgfxImageFromROMtoFatFS("S|corner2.png", "F|corner2");
    writeUgfxImageFromROMtoFatFS("S|corner3.png", "F|corner3");
    writeUgfxImageFromROMtoFatFS("S|corner4.png", "F|corner4");

    writeUgfxImageFromROMtoFatFS("S|batteryIcon.png", "F|batteryIcon");
    writeUgfxImageFromROMtoFatFS("S|oilIcon.png", "F|oilIcon");
    writeUgfxImageFromROMtoFatFS("S|tempIcon.png", "F|tempIcon");
    writeUgfxImageFromROMtoFatFS("S|fuel.png", "F|fuelIcon");
    writeUgfxImageFromROMtoFatFS("S|fuelGauge.png", "F|fuelGauge");
}
